version: "3.3"

services:
    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        ports:
            - "3001:3000"
        env_file: grafana/configuration.env
        volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning/:/etc/grafana/provisioning/
        - ./grafana/dashboards/:/var/lib/grafana/dashboards/
volumes:
  grafana_data: {}